services:
  ai-assistant-web:
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_S3_HOST=${AWS_S3_HOST}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - DB_FILE=${DB_FILE}
    - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    - GTAG=${GTAG}
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - PAGE_MATCH=${PAGE_MATCH}
    - PROMPT_CONTEXT=${PROMPT_CONTEXT}
    - REACT_APP_COLOR=${REACT_APP_COLOR}
    - REACT_APP_DOCS_AMOUNT=${REACT_APP_DOCS_AMOUNT}
    - REACT_APP_DOCS_LANG=${REACT_APP_DOCS_LANG}
    - REACT_APP_DOCS_LANG_CODE=${REACT_APP_DOCS_LANG_CODE}
    - REACT_APP_DOCS_MULTILANG=${REACT_APP_DOCS_MULTILANG}
    expose:
    - 8080/tcp
    image: morriz/ai-assistant:main
    dns:
    - 172.30.0.253
    restart: unless-stopped
    healthcheck:
      interval: 1m
      retries: 3
      start_interval: 1s
      start_period: 10s
      test:
      - CMD
      - sh
      - -c
      - 'test ! -f /tmp/drain && node -e "require(''http'').get(''http://localhost:8080'',
        (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on(''error'', () => process.exit(1))"'
      timeout: 5s
