services:
  ai-assistant-web:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_S3_HOST=minio.srv.instrukt.ai
      - AWS_S3_HOST_BUCKET=minio.srv.instrukt.ai
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DB_FILE=${DB_FILE}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GTAG=${GTAG}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PAGE_MATCH=${PAGE_MATCH}
      - PROMPT_CONTEXT=${PROMPT_CONTEXT}
      - REACT_APP_COLOR=${REACT_APP_COLOR}
      - REACT_APP_DOCS_AMOUNT=${REACT_APP_DOCS_AMOUNT}
      - REACT_APP_DOCS_LANG=${REACT_APP_DOCS_LANG}
      - REACT_APP_DOCS_LANG_CODE=${REACT_APP_DOCS_LANG_CODE}
      - REACT_APP_DOCS_MULTILANG=${REACT_APP_DOCS_MULTILANG}
      - OPENAI_MODEL=${OPENAI_MODEL}
    extra_hosts:
      - minio.srv.instrukt.ai:192.168.1.30
    expose:
      - 8080/tcp
    image: morriz/ai-assistant:main
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          wget -q -T 5 -O - --header='Host: utrecht.ai-assistent.app'
          http://127.0.0.1:8080/chatapi/health | grep -q '"status":"ok"'
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
