services:
  minio-app:
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    expose:
      - 9001/tcp
      - 9000/tcp
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    healthcheck:
      interval: 30s
      retries: 3
      test:
        - CMD-SHELL
        - timeout 10 sh -c 'curl -f http://localhost:9000/minio/health/live || exit
          1'
      timeout: 15s
